import React from 'react';
import NewChallengeForm from '../../components/hr/NewChallengeForm';
import HRChallengeList from '../../components/hr/HRChallengeList';
import AIAssistant from '../../components/hr/AIAssistant';

const HRChallengesPage = () => {
    // This state and function allow the challenge list to be updated
    // automatically when a new challenge is created.
    const [refreshKey, setRefreshKey] = React.useState(0);
    const [aiGeneratedData, setAiGeneratedData] = React.useState(null);

    const handleChallengeCreated = () => {
        setRefreshKey(prevKey => prevKey + 1);
    };

    // Function for when the AI generates a usable challenge
    const handleAIChallenge = (challengeData) => {
        // Pre-fill the form with AI data
        setAiGeneratedData(challengeData);
        console.log('Challenge generated by AI:', challengeData);
    };

    return (
        <div className="space-y-8">
            <div>
                <h1 className="text-4xl font-bold text-gray-800">Challenge Management</h1>
                <p className="text-gray-500 mt-1">Create and manage engagement challenges for employees.</p>
            </div>
            
            {/* Top section with AI Assistant and Form side by side */}
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-8 items-start">
                <div className="space-y-6">
                    {/* AI Assistant */}
                    <AIAssistant onChallengeGenerated={handleAIChallenge} />
                </div>
                <div className="space-y-6">
                    {/* Component to create new challenges */}
                    <NewChallengeForm 
                        onChallengeCreated={handleChallengeCreated} 
                        aiGeneratedData={aiGeneratedData}
                        onDataUsed={() => setAiGeneratedData(null)}
                    />
                </div>
            </div>
            
            {/* Bottom section with Challenge List occupying full width */}
            <div className="w-full">
                <HRChallengeList key={refreshKey} />
            </div>
        </div>
    );
};

export default HRChallengesPage;